/*
 * Java bean class for entity "brands" 
 * Created on 2021-04-22 ( Date ISO 2021-04-22 - Time 15:23:42 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package int221.project.models;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Brands {

	@Id
    private int        brandid      ; // Id or Primary Key
    private String     name         ;

	public void setBrandid( int brandid ) {
        this.brandid = brandid ;
    }

	public int getBrandid() {
        return this.brandid;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

}
