/*
 * Java bean class for entity "colors" 
 * Created on 2021-04-22 ( Date ISO 2021-04-22 - Time 15:23:42 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package int221.project.models;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Colors
{
    
	@Id
    private int        colorid      ; // Id or Primary Key
    private String     colorcode    ;
    private String     name         ;

	public void setColorid( int colorid ) {
        this.colorid = colorid ;
    }
    
	public int getColorid() {
        return this.colorid;
    }

    public void setColorcode( String colorcode ) {
        this.colorcode = colorcode;
    }
    
    public String getColorcode() {
        return this.colorcode;
    }

    public void setName( String name ) {
        this.name = name;
    }
    
    public String getName() {
        return this.name;
    }

}
