/*
 * Java bean class for entity "productcolors" 
 * Created on 2021-04-22 ( Date ISO 2021-04-22 - Time 15:23:42 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package int221.project.models;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Getter;
import lombok.Setter;

@Entity
//@IdClass(ProductColorsId.class)
@JsonIgnoreProperties(value = {"productcolors"})
public class Productcolors implements Comparable<Productcolors>
{
//	@Id
//	private Integer productcode ; // Id or Primary Key
//  @Id 
//  private Integer colorid ; // Id or Primary Key
	
	@EmbeddedId
	private ProductColorsId productcolors;

    @ManyToOne(optional = false)
    @MapsId("productcode")
    @JoinColumn(name = "productcode")
    @JsonBackReference
    Products products;

	@ManyToOne(optional = false)
    @MapsId("colorid")
    @JoinColumn(name = "colorid")
    Colors colors;
    
//	public Productcolors() {
//}
//
//	public Productcolors(Integer productcode, Integer colorid) {
//	this.productcode = productcode;
//	this.colorid = colorid;
//}
//
//	public Integer getProductcode() {
//		return productcode;
//	}
//
//	public void setProductcode(Integer productcode) {
//		this.productcode = productcode;
//	}
//
//	public Integer getColorid() {
//		return colorid;
//	}
//
//	public void setColorid(Integer colorid) {
//		this.colorid = colorid;
//	}

	public Products getProducts() {
		return products;
	}

	public ProductColorsId getProductcolors() {
		return productcolors;
	}

	public void setProductcolors(ProductColorsId productcolors) {
		this.productcolors = productcolors;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Colors getColors() {
		return colors;
	}

	public void setColors(Colors colors) {
		this.colors = colors;
	}

	@Override
	public int compareTo(Productcolors o) {
		return this.productcolors.getProductcode() - o.productcolors.getProductcode() ;
	}

}
