/*
 * Java bean class for entity "productcolors" 
 * Created on 2021-04-22 ( Date ISO 2021-04-22 - Time 15:23:42 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package int221.project.models;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@Entity
@JsonIgnoreProperties(value = {"productcolors"})
public class Productcolors implements Comparable<Productcolors>
{
	
	@EmbeddedId
	private ProductColorsId productcolors;

    @ManyToOne(optional = false)
    @MapsId("productcode")
    @JoinColumn(name = "productcode")
    @JsonBackReference
    Products products;

	@ManyToOne(optional = false)
    @MapsId("colorid")
    @JoinColumn(name = "colorid")
    Colors colors;
    
	public Products getProducts() {
		return products;
	}

	public ProductColorsId getProductcolors() {
		return productcolors;
	}

	public void setProductcolors(ProductColorsId productcolors) {
		this.productcolors = productcolors;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Colors getColors() {
		return colors;
	}

	public void setColors(Colors colors) {
		this.colors = colors;
	}

	@Override
	public int compareTo(Productcolors o) {
		return this.productcolors.getColorid() - o.productcolors.getColorid() ;
	}

}
