services:
  backend:
    build: .
    image: backend:latest
    ports:
      - "8083:8083"
    networks:
      test:
        ipv4_address: 172.23.2.2
networks:
  test:
    external:
      name: testNetwork2